"""Data IO for Step 2.

Loads the Step 1 customer-grouped splits and validated auxiliary tables
(customers, recovery_actions, action_outcomes) and exposes a *leakage-safe*
per-transaction dataset with:

* customer attributes joined by ``customer_id``
* action attributes joined by ``action_id``
* per-(transaction, action) target ``recovered`` from ``action_outcomes``
  (Step 1's historical attempts are the *only* supervision signal — we do
  not import the hidden ground-truth model).

Splits are loaded exactly as written by Step 1. We never reassign customers
across splits, and we never introduce aggregates that span split boundaries.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional

import numpy as np
import pandas as pd

from data_core.config import (
    SPLITS_DIR,
    SPLIT_PATH_TEMPLATE,
    VALIDATED_DIR,
)
from data_core.io import read_frame

from .config import RECOVERED_STATUSES


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _normalize_int(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce").astype("Int64")


def _load_customers() -> pd.DataFrame:
    p = VALIDATED_DIR / "customers.csv"
    if not p.exists():
        raise FileNotFoundError(f"customers.csv not found at {p}. Run Step 1 first.")
    df = read_frame(p, "customers")
    df["customer_tenure_days"] = _normalize_int(df["customer_tenure_days"])
    return df


def _load_recovery_actions() -> pd.DataFrame:
    p = VALIDATED_DIR / "recovery_actions.csv"
    if not p.exists():
        raise FileNotFoundError(f"recovery_actions.csv not found at {p}. Run Step 1 first.")
    return read_frame(p, "recovery_actions")


def _load_action_outcomes() -> pd.DataFrame:
    p = VALIDATED_DIR / "action_outcomes.csv"
    if not p.exists():
        raise FileNotFoundError(f"action_outcomes.csv not found at {p}. Run Step 1 first.")
    return read_frame(p, "action_outcomes")


def _load_split(name: str, splits_dir: Path = SPLITS_DIR) -> pd.DataFrame:
    p = splits_dir / SPLIT_PATH_TEMPLATE.format(name=name)
    if not p.exists():
        raise FileNotFoundError(f"Split {name} not found at {p}. Run Step 1 first.")
    df = read_frame(p, "transactions")
    df["retry_count"] = _normalize_int(df["retry_count"])
    df["days_overdue"] = _normalize_int(df["days_overdue"])
    return df


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
@dataclass
class Step2Datasets:
    """Container for all Step 2 inputs (per-split transactions + aux tables)."""

    splits: Dict[str, pd.DataFrame]            # name -> transactions DataFrame
    customers: pd.DataFrame                    # one row per customer
    recovery_actions: pd.DataFrame             # one row per action
    action_outcomes: pd.DataFrame              # historical attempts

    def action_ids(self) -> list[str]:
        return self.recovery_actions["action_id"].tolist()


def load_step2_data(
    splits_dir: Path = SPLITS_DIR,
    validated_dir: Path = VALIDATED_DIR,
) -> Step2Datasets:
    """Load all Step 2 inputs from disk."""
    customers = _load_customers()
    actions = _load_recovery_actions()
    outcomes = _load_action_outcomes()

    splits: Dict[str, pd.DataFrame] = {}
    for name in ("train", "val", "test", "demo"):
        try:
            splits[name] = _load_split(name, splits_dir)
        except FileNotFoundError:
            # demo may be optional for some experiments
            continue
    return Step2Datasets(
        splits=splits,
        customers=customers,
        recovery_actions=actions,
        action_outcomes=outcomes,
    )


# ---------------------------------------------------------------------------
# Label generation (leakage-safe by construction)
# ---------------------------------------------------------------------------
def build_labeled_pairs(
    transactions: pd.DataFrame,
    action_outcomes: pd.DataFrame,
    recovery_actions: pd.DataFrame,
    seed: int,
) -> pd.DataFrame:
    """Construct the supervised (transaction_id, action_id, recovered) frame.

    For every (transaction, action) cartesian product:

    * recovered = 1  iff there is an action_outcomes row for (txn, action)
      with recovery_status in RECOVERED_STATUSES and recovered_amount > 0;
    * recovered = 0  otherwise (no attempt row, or failed attempt).

    The action_outcomes table was generated by Step 1 *deterministically*
    ahead of any modeling and is part of the same validated dataset, so using
    it as a label source does **not** introduce train/test leakage (no model
    ever sees the test split during fit). However, we **do not** aggregate
    future outcomes relative to a transaction's timestamp — the historical
    action_outcomes rows are all realized at or before the dataset reference
    date (Step 1 enforces ``outcome_timestamp <= reference_date``), so using
    them as labels is leakage-safe with respect to *future* information.
    """
    if transactions.empty:
        return pd.DataFrame(columns=["transaction_id", "action_id", "recovered", "recovered_amount"])

    txn_ids = transactions["transaction_id"].tolist()
    act_ids = recovery_actions["action_id"].tolist()

    pairs = pd.MultiIndex.from_product(
        [txn_ids, act_ids], names=["transaction_id", "action_id"]
    ).to_frame(index=False)

    if action_outcomes.empty:
        pairs["recovered"] = 0
        pairs["recovered_amount"] = 0.0
        pairs["had_attempt"] = False
        return pairs

    # Aggregate outcomes by (txn, action). Multiple outcomes for the same
    # (txn, action) should not occur in synthetic data, but be defensive.
    out = action_outcomes.copy()
    out["recovered_amount"] = pd.to_numeric(out["recovered_amount"], errors="coerce").fillna(0.0)
    is_recovered = out["recovery_status"].isin(RECOVERED_STATUSES) & (out["recovered_amount"] > 0.0)
    out["_recovered_flag"] = is_recovered.astype(int)
    out["_amount"] = out["recovered_amount"]

    agg = (
        out.groupby(["transaction_id", "action_id"], as_index=False)
           .agg({"_recovered_flag": "max", "_amount": "max"})
           .rename(columns={"_recovered_flag": "recovered", "_amount": "recovered_amount"})
    )

    pairs = pairs.merge(agg, on=["transaction_id", "action_id"], how="left")
    pairs["recovered"] = pairs["recovered"].fillna(0).astype(int)
    pairs["recovered_amount"] = pairs["recovered_amount"].fillna(0.0)
    pairs["had_attempt"] = pairs["recovered_amount"].notna()
    return pairs


def assert_customer_split_isolation(
    splits: Dict[str, pd.DataFrame],
) -> None:
    """Raise AssertionError if any customer appears in two splits."""
    seen: Dict[str, str] = {}
    for name, df in splits.items():
        for cid in df["customer_id"].unique().tolist():
            prev = seen.get(cid)
            if prev is not None and prev != name:
                raise AssertionError(
                    f"customer {cid} in two splits: {prev!r} and {name!r}"
                )
            seen[cid] = name


__all__ = [
    "Step2Datasets",
    "load_step2_data",
    "build_labeled_pairs",
    "assert_customer_split_isolation",
]
